"""empty message

Revision ID: e30e00eed9f8
Revises: 4275fac7bd43
Create Date: 2023-08-31 16:34:29.643148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e30e00eed9f8"
down_revision = "4275fac7bd43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("completed", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("completed", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
